# Generated by Django 2.2.2 on 2020-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20201211_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='brief',
            field=models.CharField(default='small brief introduction', max_length=100),
            preserve_default=False,
        ),
    ]
